const themeColor = (name) => `rgb(var(--color-${name}) / <alpha-value>)`

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      animation: {
        slideDown: 'slideDown 0.3s ease-out',
      },
      keyframes: {
        slideDown: {
          '0%': { opacity: '0', transform: 'translate(-50%, -10px)' },
          '100%': { opacity: '1', transform: 'translate(-50%, 0)' },
        },
      },
      colors: {
        surface: themeColor('surface'),
        'surface-dim': themeColor('surface-dim'),
        'surface-bright': themeColor('surface-bright'),
        'surface-container-lowest': themeColor('surface-container-lowest'),
        'surface-container-low': themeColor('surface-container-low'),
        'surface-container': themeColor('surface-container'),
        'surface-container-high': themeColor('surface-container-high'),
        'surface-container-highest': themeColor('surface-container-highest'),
        'on-surface': themeColor('on-surface'),
        'on-surface-variant': themeColor('on-surface-variant'),
        'inverse-surface': themeColor('inverse-surface'),
        'inverse-on-surface': themeColor('inverse-on-surface'),
        outline: themeColor('outline'),
        'outline-variant': themeColor('outline-variant'),
        'surface-tint': themeColor('surface-tint'),
        primary: themeColor('primary'),
        'on-primary': themeColor('on-primary'),
        'primary-container': themeColor('primary-container'),
        'on-primary-container': themeColor('on-primary-container'),
        'inverse-primary': themeColor('inverse-primary'),
        secondary: themeColor('secondary'),
        'on-secondary': themeColor('on-secondary'),
        'secondary-container': themeColor('secondary-container'),
        'on-secondary-container': themeColor('on-secondary-container'),
        tertiary: themeColor('tertiary'),
        'on-tertiary': themeColor('on-tertiary'),
        'tertiary-container': themeColor('tertiary-container'),
        'on-tertiary-container': themeColor('on-tertiary-container'),
        background: themeColor('background'),
        'on-background': themeColor('on-background'),
        'surface-variant': themeColor('surface-variant'),
        error: themeColor('error'),
        'on-error': themeColor('on-error'),
        'error-container': themeColor('error-container'),
        'on-error-container': themeColor('on-error-container'),
        success: themeColor('success'),
        'on-success': themeColor('on-success'),
        'success-container': themeColor('success-container'),
        'on-success-container': themeColor('on-success-container'),
        warning: themeColor('warning'),
        'on-warning': themeColor('on-warning'),
        'warning-container': themeColor('warning-container'),
        'on-warning-container': themeColor('on-warning-container'),
        info: themeColor('info'),
        'on-info': themeColor('on-info'),
        'info-container': themeColor('info-container'),
        'on-info-container': themeColor('on-info-container'),
      },
      fontFamily: {
        'hanken': ['Hanken Grotesk', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        'base': '4px',
        'xs': '0.5rem',
        'sm': '1rem',
        'md': '1.5rem',
        'lg': '2.5rem',
        'xl': '4rem',
        'gutter': '24px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container': '1440px',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
      },
      backdropBlur: {
        'glass-sm': '12px',
        'glass-md': '20px',
        'glass-lg': '24px',
      },
    },
  },
  plugins: [],
}
