/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Crystal Finance System - White Mode (preserving original blue branding)
        surface: '#ffffff',
        'surface-dim': '#f8fafc',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f5f9',
        'surface-container': '#e2e8f0',
        'surface-container-high': '#cbd5e1',
        'surface-container-highest': '#94a3b8',
        'on-surface': '#0f172a',
        'on-surface-variant': '#475569',
        'inverse-surface': '#f1f5f9',
        'inverse-on-surface': '#1e293b',
        outline: '#94a3b8',
        'outline-variant': '#e2e8f0',
        'surface-tint': '#afc6ff',
        primary: '#afc6ff',
        'on-primary': '#082e68',
        'primary-container': '#34518d',
        'on-primary-container': '#afc6ff',
        'inverse-primary': '#415d9a',
        secondary: '#afc6ff',
        'on-secondary': '#002d6c',
        'secondary-container': '#134490',
        'on-secondary-container': '#93b4ff',
        tertiary: '#64748b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#f1f5f9',
        'on-tertiary-container': '#0f172a',
        background: '#ffffff',
        'on-background': '#0f172a',
        'surface-variant': '#e2e8f0',
        // Error colors for status indicators
        error: '#dc2626',
        'on-error': '#ffffff',
        'error-container': '#9b2a2a',
        'on-error-container': '#f7abab',
      },
      fontFamily: {
        'hanken': ['Hanken Grotesk', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        'base': '4px',
        'xs': '0.5rem',
        'sm': '1rem',
        'md': '1.5rem',
        'lg': '2.5rem',
        'xl': '4rem',
        'gutter': '24px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container': '1440px',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
      },
      backdropBlur: {
        'glass-sm': '12px',
        'glass-md': '20px',
        'glass-lg': '24px',
      },
    },
  },
  plugins: [],
}
